### ISSUE TITLE
Never do curl ... | sh especially without ssl

### ISSUE THREAD

**Issue by mrThe** [csweichel/lama#3]
http://lama.sh/ does not force the ssl connection, so anyone can intercept connection and an user can be attacked.

But even with ssl `curl ... | sh` is an awful bad practice.

**Comment by csweichel** [comment]
Forcing https would unfortunately break the simple `curl` and require `curl -L`.

W.r.t. to `curl ... | sh` that's hardly different from something like `npx http-server`. In that sense: don't run this in sensitive environments (much like you *hopefully* would not run `npx anything` there) with the difference that you can inspect easily what your curl is going to do.
